foundriesio/jobserv

- examples/projects/entrypoint.yml
- examples/projects/run-as.yml
- jobserv/project-schema.yml
- jobserv/project.py
- runner/jobserv_runner/handlers/simple.py
We have two issues in CI right now that both require overriding
default docker-run behavior.
1) A container with a non-root user may not be able to save artifacts
If the worker is run as root, then /archive is owned by root and the
the container user won't be able to write to it.
2) A container may have an entrypoint we don't want to run
A container like:
https://github.com/zephyrproject-rtos/docker-image
Includes an entrypoint we don't really want to run in our CI.
> schema: Add docker overrides for entrypoint and user

- runner/jobserv_runner/handlers/git_poller.py
- tests/runner/test_handler_git.py
This is effectively a no-op for repos that don't have them, but
makes things a lot easier for projects using them when they are
present
> runner: Support Git repos with submodules

- jobserv/api/health.py
- jobserv/api/run.py
- jobserv/models.py
- runner/jobserv_runner/handlers/simple.py
- runner/jobserv_runner/jobserv.py
- runner/jobserv_runner/logging.py
- tests/runner/test_handler_simple.py
- tests/runner/test_logging.py
- tests/test_api_health.py
- tests/test_api_run.py
- tests/test_models.py
This change allows you to do something like:
~~~
curl -X POST -H "X-JOBSERV-CANCEL: 1" https://api.foundries.io/projects/lmp/builds/X/runs/foo/
~~~
The Run will then be mark as CANCELLING in the database and API. The JobServ worker will eventually see this as it reports its run status to the server and forcefully exit.
Its not totally foolproof:
* A Run stuck uploading a lot of artifacts won't get cancelled until its done uploading because it won't see this state change.
* A Run that just works for a long time and produces no stderr/stdout data will hang because its not reporting anything to the server.
However, those are edge cases which *could* be covered but rarely if ever happen in practice.
> Add ability to cancel a Run

- jobserv/models.py
- jobserv/project.py
- tests/test_api_worker.py
- tests/test_project.py
We hit the following issue in production with a synchronous project:
* long running build with one run for the amd64 host-tag is RUNNING
* a new build for this project is QUEUED with:
run-1 - host-tag=amd64
run-2 - host-tag=armhf
run-3 - host-tag=aarch64
The query we have to find candidates is filtering on host-tag, so we
accidentally allowed run-2 and run-3 to get executed before the
first long running build was done.
The code did handle the "run-1" properly since their host tags matched.
The fix here is to handle the host-tag filtering *after* we find our
candidates. Since we no longer filter inside SQL, we can go back to
letting our host-tags be in python's fnmatch style format.
I also renamed the runs in the test to make them a bit
easier to understand.
Signed-off-by: Andy Doan …
> Fix synchronous project build logic with tags

- runner/jobserv_runner/cmd.py
pyton3.4 and greater return an empty list, so we can be simplify how we
call the poll api.
Additionally the timeout value was wrong. It was assuming seconds and
the expected value is milliseconds. This leads to some aggressive
polling and we really don't have anything useful to do while we wait on
output.
> runner: Improve command polling logic

- runner/jobserv_runner/handlers/git_poller.py
We often have users with git submodules that try to pull down
repositories like:
~~~
git@github.com:<company>/repo
~~~
This is great for local development but doesn't work well in CI. In the
past we've suggested users set their submodules to https. This is a bit
of a pain for them, and this change allows us to manage it.
> handlers: Try https on github submodules

- runner/jobserv_runner/handlers/git_poller.py
- tests/runner/test_handler_git.py
The complexity of our git configuration is growing. We've already
started (ab)using $HOME for .netrc. This does the same to build up a
.gitconfig that will be easier to understand.
This also fixes a real issue. The "-c http.extraheaders" breaks
repositories with git-lfs. git-lfs was only working with submodules.
This feels like a bug in git-lfs but this fixes it also.
> runner: Use real .gitconfig

- runner/jobserv_runner/handlers/simple.py
Not great, but docker now rate-limits container pulling. This change
allows us to copy our host's config into the run's container. Then
a script like ci-scripts's apps/build.sh can use this for its docker
config.
> runner: Copy docker host config into container

- jobserv/notify.py
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>
> notify: use build.as_json() to compose webhook payload

- jobserv/git_poller.py
RAW files are not programmatically accessible buy '/raw' endpoint anymore.
Behaviour discovered after upgrade from v11 to v13.
Fix is aimed to use repository API instead of /raw endpoint.
Signed-off-by: kostyapenkov <kostya.penkov@foundries.io>
> Fix URL for raw files in GitLab

- jobserv/api/build.py
- jobserv/api/run.py
- jobserv/models.py
- tests/test_api_build.py
- unit-test.sh
In the past we only cancelled Runs in RUNNING. This is really annoying
when you have a bunch of things QUEUED and want to clean them up.
> api: Improve ability to cancel a run

- jobserv_worker.py
Worker did ignore `concurrent_runs` from config.
Capacity of each worker always was 2 runs, despite other number
specified in config.
Signed-off-by: kostyapenkov <kostya.penkov@foundries.io>
> worker: use 'concurrent_runs' from config

- jobserv/models.py
- tests/test_api_worker.py
We weren't taking into account that build ids come from multiple
projects
> fixup! models: Fix scheduler issue with synchronous projects

- Dockerfile
- jobserv/api/run.py
- jobserv/models.py
- requirements.txt
- tests/test_api_worker.py
We have a bug where a synchronous project can have CI runs
mis-scheduled. Here's the simplest flow:
* Two builds (one run each) builds for project get queued, 1 and 2.
* Build 1's run's goes into UPLOADING
* A worker check's in for work and gets assigned Build 2's run
The scheduler needs to filter on uploading as well as running.
> models: Account for UPLOADING runs in sync projects

- jobserv/models.py
- migrations/versions/8c2f916d3b24_.py
We've hit a release notes for the LmP with 129K text. This change only
works for mysql, so was done in a way that won't break normal local
sqlite development flows.
> models: Increase column length for Build annotation

- runner/jobserv_runner/handlers/git_poller.py
- runner/jobserv_runner/handlers/simple.py
- tests/runner/test_handler_simple.py
We get enough support issues with git-clone failing, that making this
retriable would help a bunch. 9 times out of 10 this solves the issue.
> runner: Make git operations retriable

- jobserv/api/health.py
The host tag is important for understanding why things are queued up.
> api: Include host_tag for status API

- jobserv_worker.py
- runner/jobserv_runner/handlers/simple.py
- tests/runner/test_handler_simple.py
CI jobs may launch containers that can eat up so much memory that the OOM process starts to kill the wrong stuff. This helps a worker protect itself and have a CI job fail more gracefully. eg "exit 137" means the process ran out of memory.
> worker: Allow workers to limit container memory usage

- jobserv/api/run.py
- jobserv/api/worker.py
- jobserv/project.py
- jobserv/storage/base.py
- jobserv/trigger.py
- tests/test_api_run.py
- tests/test_api_test.py
- tests/test_project.py
Having to consider the run definition to be a string is quite tedious for callers.
> storage: Handle rundef as a dictionary

- runner/jobserv_runner/handlers/simple.py
We don't make the test logs very clear about what junit test failed. We do show the test results, but it's not super clear reading the console log. This will help people more easily see they need to go dig into test results.
> runner: Log info about failed tests

- jobserv/api/worker.py
- jobserv_worker.py
This allows us to run a jobserv instance with different URLs so that:
* the runs can trust certs for "staging" type servers
* the runs know the URL of the server
> Updates for more flexible workers

- jobserv/worker.py
- tests/test_worker.py
We tend to exhaust of shared volume every few months because the number of offline worker ping logs grows. We almost don't even need  the pings log. All the info is getting sent to StatsD. However, its easier to "fix" this by deleting them as they go offline.
> worker: Remove offline worker ping logs

- jobserv/worker.py
This can happen on fresh installs where the system has never had a worker check in. If we have no workers - there's no point trying to see if we need surges enabled.
> worker: Don't check for surges if there's no WORKER_DIR

- jobserv/worker.py
A run stuck in cancelling shouldn't wait 12 hours. It winds up blocking future work from happening, so just give 10 minutes for the worker to clean up and then move on.
> worker: Create unique threshold for stuck/cancelling

- jobserv/worker.py
Signed-off-by: Camila Macedo <camila.macedo@foundries.io>
> fix: skip worker checks when WORKDIR does not exist

- requirements.txt
All version <3.0.1 have a CVE:
https://nvd.nist.gov/vuln/detail/CVE-2023-46136
The release notes for 3.0 are relatively small:
* Remove previously deprecated code. #2768
* Deprecate the __version__ attribute. Use feature detection, or importlib.metadata.version("werkzeug"), instead. #2770
* generate_password_hash uses scrypt by default. #2769
* Add the "werkzeug.profiler" item to the WSGI environ dictionary passed to ProfilerMiddleware’s filename_format function. It contains the elapsed and time values for the profiled request. #2775
* Explicitly marked the PathConverter as non path isolating. #2784
Jobserv does the PathConverter. However, we've tested this patch in gavelci.us w/o any issues.
> requirements: bump werkzeug for CVE

- Dockerfile
Following the issue faced:
```
$ kubectl logs jobserv-backup-manual-20240228184829-vrpzj -n ci mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect
{"written_at": "2024-02-28T18:48:41.294Z", "written_ts": 1709146121294839000, "msg": "Unable to send email:_|  Content-Type: text/plain; charset=\"us-ascii\"_|  MIME-Version: 1.0_|  Content-Transfer-Encoding: 7bit_|  To: _|  From: bot@foundries.io_|  Subject: jobserv: DB Backup Failed_|  _|  Traceback (most recent call last):_|    File \"/srv/jobserv/jobserv/notify.py\", line 238, in wrapper_|      func(*args, **kwargs)_|    File \"/srv/jobserv/jobserv/app.py\", line 300, in backup_| …
```
> Began to build image with the plugin mariadb-connector-c to fix issue to connect in the database from jobserv

- jobserv/api/project.py
- jobserv/models.py
- tests/test_api_project_triggers.py
This ensures we only use sane names for secrets and disallow things like a "/" in the name. This was tested against all secrets in our DB.
> models: Validate secret names in triggers

- jobserv/api/__init__.py
We've had a long standing bug where code in modules will do something like raise an HTTPException. Rather than return that, our default 500 exception handler gets hit and we wrap something like a 401 error with a 500 error.
> api: Fix long standing error handling issue

- examples/projects/github-multi-branch.yml
- jobserv/api/github.py
- tests/test_api_github.py
This allows us to have different CI runs based on the github branch the PR is targetted to.
> api: Teach github pr to handle multiple branches

- dev-shell
- jobserv/api/worker.py
- jobserv/models.py
- jobserv/settings.py
- jobserv/worker.py
- jobserv_worker.py
- tests/test_api_worker.py
This can be a handy feature in certain cases. Especially for people with ephemeral workers that need to share some debug data.
> Add mechanism for workers to upload log data

- jobserv/storage/gce_storage.py
GCP suffered a massive outage today. The thing that affected us most was that calls to `get_bucket` were timing out. Many parts of code need a reference to the Storage object, but they don't need the bucket. For example, a CI run will mostly be streaming console logs to disk.
By lazy loading the bucket reference, we only pay the price of a GCS failure in code paths that require it.
> storage: Lazy load gcs bucket
