.jobserv.yml, jobserv/api/github.py, jobserv/api/gitlab.py, jobserv/api/run.py, jobserv/git_poller.py, jobserv/lava_reactor.py, jobserv/project.py, requirements.txt, simulator.py, tests/test_project.py
The real issue here is that I should have never used yaml.load in the
first place. However, I'm fixing both things here.
=> CVE-2017-18342 - Fix pyyaml usage

jobserv/models.py, tests/test_api_worker.py
There's a problem with the current logic: A synchronous project with
a build containing multiple runs (say multi-arch docker containers)
will run sequentially.
This query is becoming insane and I think the new approach is probably
going to be *more* efficient since its so much less stress on the
database coupled with the fact that we are never going to have that
many concurrent runs.
The new approach is to find out everything we need about QUEUED and
RUNNING runs. We can then loop through these results in a single
pass to know if there's a run we can schedule.
=> models: Handle synchronous project builds better

jobserv/git_poller.py, tests/test_git_poller.py
added ability to skip when flag is present
=> skipping [skip ci] and [ci skip]

jobserv/git_poller.py
=> git-poller: Fix mypy warnings

.gitignore, jobserv/api/project.py, jobserv/models.py, tests/test_api_project.py
adds ability to delete keywords by sending `null`  entries
=> added keyword deletion

docker-compose.yml, docker_run_worker_monitor.sh, docs/docker-compose.md, jobserv_worker.py
made calls regarding platform via native python and also utilizing work from plutil
=> fixes first run

jobserv/api/build.py, tests/test_api_build.py
getting 500s from when calling ".../projects/jobserv/builds/../project.yml"
=> project.yml mistype error

jobserv/jsend.py
gives pagination primitives in standard payload
=> updated pagination output

runner/jobserv_runner/handlers/git_poller.py
=> runner: Detect git-lfs and extract if needed

.jobserv.yml, examples/projects/shared-volume.yml, jobserv/project-schema.yml, jobserv/project.py, jobserv_worker.py, runner/jobserv_runner/handlers/simple.py
This can be really useful for CI jobs that can benefit from something
like a shared public cache.
=> Add the notion of read-only shared volumes

jobserv/api/run.py, tests/test_api_run.py
Fixes bug #45. If a trigger has no notification settings, we should
check if it had a parent trigger that *did*.
=> api: Inherit trigger's notification settings

jobserv/flask.py, tests/test_api_run.py
Signed-off-by: Mike <mike.sul@foundries.io>
=> app: Handle Werkzeug's 404 errors in flask app

jobserv/models.py, jobserv/storage/base.py
This mixes in the run-id into the key so that you'd need to compromise both the DB and the k8s secret in order to decrypt the secrets.
=> Store rundef secrets symetrically encrypted

jobserv_worker.py
There are times when the host system may want to know about CI Runs starting and stopping. This provides a very primitive interface for handling it.
=> worker: Add notion of callbacks

jobserv/api/build.py, jobserv/models.py, tests/test_api_build.py
Signed-off-by: Mike <mike.sul@foundries.io>
=> api: Add handler to register external CI builds

jobserv/api/build.py, tests/test_api_build.py
Signed-off-by: Mike <mike.sul@foundries.io>
=> api: Add ability to get an overall latest build

jobserv/api/github.py
It can become a security issue for certain types of CI jobs to allow anyone to trigger a build. This change looks for an "ok-to-test" label on the PR (if one exists for the project) before it will proceed.
=> github_pr: Look for ok-to-test label

jobserv/api/github.py, jobserv/trigger.py
This isn't super safe, but Github has limits to how long a request can take. We have builds that now trigger 40+ CI runs. The processing takes too long for github.
This change is the least invasive way to get what we need without having to refactor a bunch of code.
=> github: Commit runs from a thread

jobserv/models.py
This seems impossible but we actually saw a failure in production. Pings log isn't that important, so "this is fine"
=> models: Fix race condition in ping

jobserv_worker.py
The JWTs created for a worker have an expiration. This is largely for security. However, we hit an interesting problem with the system is really busy processing CI Runs for a specific host-tag:
* Scaler spins up worker. Let's say it JWT is valid for 4 hours
* Worker comes up and is busy for the entire time.
* Towards the end of this 4 hour window (say 3 hours and 58 minutes), the worker completes a Run. It then ask the server for more work.
* There is more work so it starts a CI run at the 3 hour and 59 minute mark.
* We start a "long" CI run. The run works fine - it gets a special api token to process the run with.
* The *dameon*, however, will start getting rejections when it checks in with the server. This results in the daemon's logic eventually deciding its "idle".
* The idle script …
=> worker: Fix issue with expiring JWT

jobserv/storage/gce_storage.py
GCS doesn't have a way to bulk delete. This makes things significantly faster. gsutil doesn't have a public API for this but I noticed they fork a bunch of process to delete so it's probably a similar hack.
=> storage: Make object deletion faster

requirements.txt
Addresses two CVEs:
https://github.com/pallets/werkzeug/blob/main/CHANGES.rst#version-306
=> requirements: Bump Werkzeug to 3.0.6
